### ISSUE TITLE
EventTarget.call(this) results in TypeError Illegal constructor.

### ISSUE THREAD

**Issue by mysterycommand** [benlesh/abort-controller-polyfill#3]
I tried using this to polyfill support for Mobile Safari < 11, and Firefox < 57 … both support `EventTarget` but it's not callable in the old JavaScript way (e.g. [`EventTarget.call(this)`](https://github.com/benlesh/abort-controller-polyfill/blob/master/index.js#L14)). It can be extended with ES6 classes (e.g. `class AbortController extends EventTarget {}`) which has [slightly wider support](https://caniuse.com/es6-class) [than AbortController](https://caniuse.com/abortcontroller), but if you don't want to go that route I think you might have to force an `EventTarget` implementation that is `call`able or use one of those old dom element/fragment delegation hacks.

If you have an idea of what direction you'd like to take, I might be able to put some time into a PR. Having a "built-in" `EventTarget` implementation _might_ also work to solve #1?

**Comment by nulladdict** [comment]
We've also hit this problem in the old Chrome version (49, last supported on Windows XP)
We worked around this by overwriting default `EventTarget` implementation unconditionally

But it would be nice, if this can be detected beforehand, probably inside the [event-target-polyfill](https://github.com/benlesh/event-target-polyfill)

**Comment by benlesh** [comment]
This should be resolved in event-target-polyfill@0.0.3

**Comment by zurfyx** [comment]
Shouldn't `event-target-polyfill` or an alternative workaround provide an instantiable `EventTarget` in the first place rather than expect users to overwrite the implementation themselves?

For reference, this is what fails: `EventTarget.call(this);`

My findings:

In the latest browser versions (Firefox 89, Chrome 90), it just blocks you from calling the constructor function directly (`EventTarget.call(this)`)

But you can still do Babel's ES6 transpilation approach: `Reflect.construct(EventTarget, [], Object.getPrototypeOf(this).constructor)`

However, in older browsers like Firefox 53, EventTarget does exist but `new EventTarget`, `EventTarget.call` and `Reflect.construct` are forbidden.

Which makes me conclude that the safest path is to provide our own EventTarget implementation whenever we're polyfilling AbortController. That said, this EventTarget does not necessarily have to live in the global scope and can be loaded and used for the sole purpose of this polyfill.

**Comment by unematiii** [comment]
This still doesn't work (`abort-controller-polyfill 0.0.4, event-target-polyfil 0.0.3`).

**Comment by nulladdict** [comment]
Can also confirm that this is still broken, we're getting errors in Firefox 52 and Chrome 49 (last supported versions on Windows XP)
